sudo: false
language: python
python: 2.7
env:
- TOX_ENV=docs
- TOX_ENV=flake8
- TOX_ENV=py27
- TOX_ENV=py33
- TOX_ENV=py34
- TOX_ENV=py35
install:
- pip install -r tests/requirements.txt
- pip install coveralls flake8 tox
- pip install .
script:
- tox -e $TOX_ENV
after_success:
- coveralls
before_script: flake8 --ignore=W391 stl tests
notifications:
  email:
    on_success: never
    on_failure: change
deploy:
  provider: pypi
  user: WoLpH
  password:
    secure: HVxDUJ6ns7G7xypuibu01ruDfO4orV5lNr1Mor003MX3HVivvKsTwWqY5K1J+J+C4mgK6ahyvanD5GahYvcWia/Y2xeH2VnytnAgo+W3AI+h72+1oaRpvQHynJ7Fz6Mc0zad0GcbQh3QuA7Pu3IOWs7buUL+MQM6d9QLTkerOvs=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: WoLpH/numpy-stl
